name: flutter_syntax_view
description: Flutter Syntax Highlighter
version: 2.2.1
authors:
  - Bader Eddine Ouaich <badereddineouaich@gmail.com>
  - Rody Davis Jr <rody.davis.jr@gmail.com> 
  - LuodiJackShen <luodijack@163.com>
  - luodijack <https://github.com/luodijack>
  - Marwén Benromdhan <https://github.com/marwenx>
homepage: https://github.com/BaderEddineOuaich/flutter_syntax_view

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  string_scanner: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
